services:
  - type: web
    name: ytdl-web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=$HOME/.deno sh -s -- -y
    startCommand: export PATH=$HOME/.deno/bin:$PATH && gunicorn app:app -w 1 --threads 8 -b 0.0.0.0:$PORT --timeout 0
    envVars:
      - key: APP_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
